name: Docker Image CI pdns-admin

on:
  push:
    tags:
      - 'pdns-admin-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF##*-}

      - name: Build and push PDNS Admin
        id: docker_build_pdns_admin
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-admin
          file: ./pdns-admin/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-admin:${{ steps.vars.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_admin.outputs.digest }}
